baseURL = "https://snowcrab.dev/"
languageCode = "en-us"
title = "Snowcrab"
enableRobotsTXT = true
summaryLength = 24

[pagination]
pagerSize = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    lineNos = false
    style = "github-dark"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
