[[main]]
name = "Posts"
url = "/posts/"
weight = 10

[[main]]
name = "Notes"
url = "/notes/"
weight = 20

[[main]]
name = "Changelog"
url = "/changelog/"
weight = 30

[[main]]
name = "Now"
url = "/pages/now/"
weight = 40

[[main]]
name = "Projects"
url = "/pages/projects/"
weight = 50

[[main]]
name = "Case Study"
url = "/pages/case-study-blank-repo-to-production/"
weight = 60

[[main]]
name = "Request"
url = "/pages/request-a-task/"
weight = 70
